name: Make Clashoo run files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Fetch latest release info
        id: fetch_latest_release
        run: |
          latest_tag=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/kenzok8/openwrt-clashoo/releases/latest | jq -r '.tag_name')
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Install makeself
        run: sudo apt-get update && sudo apt-get install -y makeself curl jq

      - name: Clone makeself repository
        run: git clone https://github.com/megastep/makeself.git

      - name: Download clashoo ipks for all architectures
        run: |
          ALL_IPKS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/kenzok8/openwrt-clashoo/releases/latest \
            | jq -r '.assets[] | select(.name | test("\\.ipk$")) | "\(.name) \(.browser_download_url)"')
          
          for ARCH in x86_64 aarch64_cortex-a53 arm_cortex-a7_neon-vfpv4; do
            mkdir -p "$ARCH"
            echo "$ALL_IPKS" | while read -r name url; do
              if echo "$name" | grep -qE "${ARCH}|_all\\.ipk"; then
                echo "⬇️ $ARCH: $name"
                curl -sL -o "${ARCH}/${name}" "$url"
              fi
            done
            ls -lh "$ARCH/"
          done

      - name: Create install.sh and pack
        run: |
          for ARCH in x86_64 aarch64_cortex-a53 arm_cortex-a7_neon-vfpv4; do
            cat <<EOF > "$ARCH/install.sh"
          #!/bin/sh
          opkg update
          if [ \$? -ne 0 ]; then
              echo "update failed"
              exit 1
          fi
          opkg install *.ipk --force-depends
          EOF
            chmod +x "$ARCH/install.sh"
          done
          mkdir -p output
          cd makeself
          for ARCH in x86_64 aarch64_cortex-a53 arm_cortex-a7_neon-vfpv4; do
            mv ../$ARCH .
            ./makeself.sh $ARCH/ ../output/clashoo_${{ env.LATEST_TAG }}_${ARCH}.run "Clashoo ${ARCH} v${{ env.LATEST_TAG }}" ./install.sh
          done

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: "Clashoo"
          name: "Clashoo-latest"
          body: "Clashoo proxy client for OpenWrt."
          files: output/*.run
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
